version: '3.8'
services:
  # 1. MongoDB Database
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  # 2. Eureka Server
  eureka-server:
    build: ./eureka-server
    ports:
      - "8085:8085"
    depends_on:
      - mongodb

  # 3. User Service
  user-service:
    build: ./user-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userData
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka/
    depends_on:
      - eureka-server
      - mongodb

  # 4. Task Service
  task-service:
    build: ./task-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userData
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka/
    depends_on:
      - eureka-server
      - mongodb

  # 5. Submission Service
  submission-service:
    build: ./submission-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/userSubmission
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka/
    depends_on:
      - eureka-server
      - mongodb

  # 6. API Gateway
  api-gateway:
    build: ./api-gateway
    ports:
      - "8090:8090"
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8085/eureka/
    depends_on:
      - eureka-server

volumes:
  mongo-data: